# Generated by Django 2.2.12 on 2020-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='deliveryboy',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='checksum',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
